### ISSUE TITLE
Tag matches also when part of hashtag is tag

### ISSUE THREAD

**Issue by thies23** [chaostreff-flensburg/superretoot#2]
When configuring the "tag" I was under the impression that the tag only matches on the full "hashtag". i.e.

`  "tag": "reisealpaka",` matches only "#reisealpaka"

Apparently it also matches hashtags that include the tag. i.e. "#ReisealpakaLeaks"

Not sure if this is intended on your side, but imho it should be at least clearer in the documentation.

**Comment by scammo** [comment]
Please have a look at: https://github.com/chaostreff-flensburg/superretoot#edited-toots
